### ISSUE TITLE
don't speed up live videos

### ISSUE THREAD

**Issue by shalva97** [Dosx001/YouTubeUtils#3]
When videos are live and have a speed of more than 1 then they start buffering

**Comment by Dosx001** [comment]
When tuning in to a YouTube livestream if your speed is greater than 1, it will play at that speed until your stream syncs up with the broadcast. Once your stream catches up with the broadcast the video should buffer for a second and default to playback speed to 1.

I tested this in my setup and everything works. Can you screen record your issue to see if this is not true?

Also, if your stream is at the "head" of the broadcast, you might see buffers here and there, because of network slowdowns between your connection, the streamer connection, and YouTube servers.

**Comment by shalva97** [comment]
the speed gets switched back to the value specified in the plugin, so one has to manually change it via addon settings. 

Here is the video

https://github.com/Dosx001/YouTubeUtils/assets/22417494/d7bf05b0-94cb-4afa-a026-4282852ba509

**Comment by Dosx001** [comment]
Oh, I see the mobile site version doesn't automatically adjust the playback speed for live streams. Sorry YouTubeUtils isn't well supported on mobile, I primarily watch YouTube on my desktop. If you find bugs and report them, I'll fix them when I have some time. 

For now, I could default the playback speed to 1 if the video is live. How does that sound?

**Comment by shalva97** [comment]
yea, that will work. Thanks in advance
